language: erlang

env:
  - LUA="lua"

install:
  - "sudo apt-get install lua5.2 luarocks tree"
  - "sudo tree /usr/local/share/lua"
  - "sudo tree /usr/local/lib/lua"
  - "sudo luarocks make rockspecs/ot-0.1.0-1.rockspec"

script: "$LUA test/test.lua"